-- Create the schools table
CREATE TABLE schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    domain VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_schools PRIMARY KEY (id)
);

-- Create the users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    school_id BIGINT NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Add unique constraint on users.email
ALTER TABLE users ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

-- Add unique constraint on schools.domain
ALTER TABLE schools ADD CONSTRAINT uc_e4b23a792077dd7ac42163ac6 UNIQUE (domain);

-- Add foreign key from users to schools
ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_SCHOOL FOREIGN KEY (school_id) REFERENCES schools (id);