-- V1__init.sql

create table if not exists schools (
  id bigint generated by default as identity primary key,
  domain varchar(255) not null,
  name varchar(255)  not null,
  constraint uq_schools_domain unique (domain)
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(255)         not null,
  password_hash varchar(255) not null,
  email_verified boolean     not null default false,
  school_id bigint           not null,
  constraint uq_users_email unique (email),
  constraint fk_users_school foreign key (school_id) references schools(id)
);

create index if not exists idx_users_school_id on users(school_id);
